redshift:
  database: db_name
  host:     hostname/ip
  username: username
  password: password
  aws_key_id: XXXXXX
  aws_secret_key: secret_key
  aws_arn: arn:aws:iam::123123123:role/rolename
  s3_bucket: bucket_name

snowflake:
  database: rs_arc
  account:  account.us-east-1
  username: username
  password: password

table_list:
  - schema.tablea
  - schemaaa.tableb

